import fs from "node:fs";
import path from "node:path";

export const ENTRY_FIELDS = [
  "id", "date", "topic", "situation", "logic", "emotion", "summary",
  "categories", "tags", "raw_input", "audio_ref", "about"
];

/** Storage boundary: replace this implementation to add a remote or cloud provider. */
export class SessionStore {
  listSessions() { throw new Error("Not implemented"); }
  getSession(_id) { throw new Error("Not implemented"); }
  createSession(_fields) { throw new Error("Not implemented"); }
  updateSession(_id, _fields) { throw new Error("Not implemented"); }
  searchSessions(_filters) { throw new Error("Not implemented"); }
}

export class LocalMarkdownSessionStore extends SessionStore {
  constructor({ dataDirectory, categories, clock = () => new Date() }) {
    super();
    this.dataDirectory = dataDirectory;
    this.sessionsDirectory = path.join(dataDirectory, "sessions");
    this.indexPath = path.join(dataDirectory, "index.json");
    this.categories = categories;
    this.clock = clock;
    fs.mkdirSync(this.sessionsDirectory, { recursive: true });
    if (!fs.existsSync(this.indexPath)) this.writeIndex([]);
  }

  listSessions({ limit = 50, before, after } = {}) {
    const items = this.readIndex().filter((item) => dateInRange(item.date, { before, after }));
    return items.slice(0, clampLimit(limit));
  }

  getSession(id) {
    const item = this.readIndex().find((entry) => entry.id === id);
    if (!item) return null;
    const filePath = path.join(this.sessionsDirectory, item.file);
    if (!fs.existsSync(filePath)) throw new Error(`Indexed session file is missing: ${item.file}`);
    return { ...parseMarkdown(fs.readFileSync(filePath, "utf8")), file: item.file };
  }

  createSession(fields = {}) {
    if (Object.hasOwn(fields, "date")) throw new Error("date is generated by the bridge when a session is created.");
    // `date` and the ID are both created from the same clock instant: date is the
    // complete ISO creation timestamp, while ID is a local, filename-safe sort key.
    const createdAt = this.now();
    const entry = normalizeEntry({ ...fields, date: formatLocalIso(createdAt) }, this.categories, this.nextId(createdAt), true);
    const file = this.uniqueFilename(entry);
    fs.writeFileSync(path.join(this.sessionsDirectory, file), serializeMarkdown(entry), "utf8");
    const index = this.readIndex();
    index.push(toIndexItem(entry, file));
    this.writeIndex(index);
    return { ...entry, file };
  }

  updateSession(id, fields = {}) {
    const current = this.getSession(id);
    if (!current) return null;
    const { file: oldFile, ...oldEntry } = current;
    if (Object.hasOwn(fields, "id") && fields.id !== id) throw new Error("A session id cannot be changed.");
    if (Object.hasOwn(fields, "date") && fields.date !== oldEntry.date) throw new Error("date is the creation timestamp and cannot be changed.");
    const entry = normalizeEntry({ ...oldEntry, ...fields, id }, this.categories, id, false);
    const desiredFile = filenameFor(entry);
    const file = desiredFile === oldFile ? oldFile : this.uniqueFilename(entry, oldFile);
    const targetPath = path.join(this.sessionsDirectory, file);
    fs.writeFileSync(targetPath, serializeMarkdown(entry), "utf8");
    if (file !== oldFile) fs.unlinkSync(path.join(this.sessionsDirectory, oldFile));
    const index = this.readIndex().map((item) => item.id === id ? toIndexItem(entry, file) : item);
    this.writeIndex(index);
    return { ...entry, file };
  }

  searchSessions({ query = "", category, tag, date_range, limit = 50, full = false } = {}) {
    if (category !== undefined) this.assertCategory(category);
    const normalizedTag = typeof tag === "string" ? tag.trim().toLocaleLowerCase() : "";
    const candidates = this.readIndex().filter((item) =>
      dateInRange(item.date, date_range || {}) &&
      (category === undefined || item.categories.includes(category)) &&
      (!normalizedTag || item.tags.some((value) => value.toLocaleLowerCase() === normalizedTag))
    );
    const needle = String(query || "").trim().toLocaleLowerCase();
    const matches = [];
    for (const item of candidates) {
      if (!needle && !full) {
        matches.push(item);
        if (matches.length >= clampLimit(limit)) break;
        continue;
      }
      const entry = this.getSession(item.id);
      if (!needle || searchableText(entry).includes(needle)) {
        matches.push(full ? entry : searchResult(entry, needle));
      }
      if (matches.length >= clampLimit(limit)) break;
    }
    return matches;
  }

  rebuildIndex() {
    const items = fs.readdirSync(this.sessionsDirectory, { withFileTypes: true })
      .filter((item) => item.isFile() && item.name.endsWith(".md"))
      .map((item) => toIndexItem(parseMarkdown(fs.readFileSync(path.join(this.sessionsDirectory, item.name), "utf8")), item.name));
    this.writeIndex(items);
    return items.length;
  }

  now() {
    const source = this.clock();
    if (!(source instanceof Date) || Number.isNaN(source.valueOf())) throw new Error("clock must return a valid Date.");
    return source;
  }

  nextId(source) {
    const pad = (value) => String(value).padStart(2, "0");
    const base = `${source.getFullYear()}-${pad(source.getMonth() + 1)}-${pad(source.getDate())}T${pad(source.getHours())}${pad(source.getMinutes())}${pad(source.getSeconds())}`;
    const ids = new Set(this.readIndex().map((item) => item.id));
    if (!ids.has(base)) return base;
    let suffix = 2;
    while (ids.has(`${base}-${pad(suffix)}`)) suffix += 1;
    return `${base}-${pad(suffix)}`;
  }

  uniqueFilename(entry, except) {
    const base = filenameFor(entry);
    if (base === except || !fs.existsSync(path.join(this.sessionsDirectory, base))) return base;
    const extension = ".md";
    const stem = base.slice(0, -extension.length);
    let suffix = 2;
    while (fs.existsSync(path.join(this.sessionsDirectory, `${stem}-${suffix}${extension}`))) suffix += 1;
    return `${stem}-${suffix}${extension}`;
  }

  readIndex() {
    const parsed = JSON.parse(fs.readFileSync(this.indexPath, "utf8"));
    if (!Array.isArray(parsed)) throw new Error("data/index.json must contain an array.");
    return parsed.sort(compareIndexItems);
  }

  writeIndex(items) {
    const sorted = [...items].sort(compareIndexItems);
    fs.writeFileSync(this.indexPath, `${JSON.stringify(sorted, null, 2)}\n`, "utf8");
  }

  assertCategory(category) {
    if (!this.categories.includes(category)) throw new Error(`category must be one of: ${this.categories.join(", ")}`);
  }
}

function normalizeEntry(input, categories, generatedId, isCreate) {
  const entry = {};
  entry.id = generatedId;
  entry.date = text(input.date ?? new Date().toISOString(), "date");
  if (Number.isNaN(new Date(entry.date).valueOf())) throw new Error("date must be a valid ISO 8601 value.");
  for (const field of ["topic", "situation", "logic", "emotion", "summary"]) entry[field] = text(input[field] ?? "", field);
  entry.categories = array(input.categories ?? [], "categories");
  const invalid = entry.categories.filter((value) => !categories.includes(value));
  if (invalid.length) throw new Error(`Invalid categories: ${invalid.join(", ")}. Allowed: ${categories.join(", ")}`);
  entry.tags = array(input.tags ?? [], "tags");
  entry.raw_input = optionalText(input.raw_input, "raw_input");
  entry.audio_ref = optionalText(input.audio_ref, "audio_ref");
  entry.about = optionalText(input.about, "about");
  entry.body = text(input.body ?? "", "body");
  if (isCreate && !entry.topic) throw new Error("topic is required when creating a session.");
  return entry;
}

function text(value, name) {
  if (typeof value !== "string") throw new Error(`${name} must be text.`);
  return value;
}
function optionalText(value, name) {
  if (value === undefined || value === null || value === "") return null;
  return text(value, name);
}
function array(value, name) {
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string")) throw new Error(`${name} must be an array of strings.`);
  return [...new Set(value.map((item) => item.trim()).filter(Boolean))];
}
function clampLimit(value) {
  const number = Number(value);
  if (!Number.isInteger(number) || number < 1) throw new Error("limit must be a positive integer.");
  return Math.min(number, 200);
}
function dateInRange(value, { before, after } = {}) {
  const timestamp = Date.parse(value);
  if (before && timestamp >= Date.parse(before)) return false;
  if (after && timestamp <= Date.parse(after)) return false;
  return true;
}
function filenameFor(entry) {
  const date = new Date(entry.date);
  const pad = (value) => String(value).padStart(2, "0");
  const prefix = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}_${pad(date.getHours())}${pad(date.getMinutes())}`;
  return `${prefix}_${slug(entry.topic)}.md`;
}
function slug(value) {
  const result = value.toLocaleLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 72);
  return result || "session";
}
function toIndexItem(entry, file) {
  if (!entry.id || !entry.date) throw new Error(`Cannot index ${file}: id and date are required.`);
  return { id: entry.id, date: entry.date, topic: entry.topic || "", categories: entry.categories || [], tags: entry.tags || [], about: entry.about || null, file };
}
function searchResult(entry, needle) {
  return {
    ...toIndexItem(entry, entry.file),
    match_context: findContext(entry, needle)
  };
}
function findContext(entry, needle) {
  if (!needle) return null;
  const fields = ["topic", "situation", "logic", "emotion", "summary", "about", "raw_input", "body"];
  for (const field of fields) {
    const value = entry[field];
    if (typeof value !== "string") continue;
    const start = value.toLocaleLowerCase().indexOf(needle);
    if (start === -1) continue;
    const radius = 100;
    const from = Math.max(0, start - radius);
    const to = Math.min(value.length, start + needle.length + radius);
    return {
      field,
      text: `${from > 0 ? "…" : ""}${value.slice(from, to)}${to < value.length ? "…" : ""}`
    };
  }
  for (const field of ["categories", "tags"]) {
    const value = (entry[field] || []).find((item) => item.toLocaleLowerCase().includes(needle));
    if (value) return { field, text: value };
  }
  return null;
}
function compareIndexItems(a, b) {
  // Dates are full creation timestamps for new sessions. ID is an explicit,
  // deterministic tiebreaker for same-second writes and legacy date-only data.
  return Date.parse(b.date) - Date.parse(a.date) || b.id.localeCompare(a.id);
}
function formatLocalIso(source) {
  const pad = (value, width = 2) => String(value).padStart(width, "0");
  const offsetMinutes = -source.getTimezoneOffset();
  const sign = offsetMinutes >= 0 ? "+" : "-";
  const absoluteOffset = Math.abs(offsetMinutes);
  return `${source.getFullYear()}-${pad(source.getMonth() + 1)}-${pad(source.getDate())}T${pad(source.getHours())}:${pad(source.getMinutes())}:${pad(source.getSeconds())}.${pad(source.getMilliseconds(), 3)}${sign}${pad(Math.floor(absoluteOffset / 60))}:${pad(absoluteOffset % 60)}`;
}
function serializeMarkdown(entry) {
  const frontmatter = ENTRY_FIELDS.map((key) => `${key}: ${JSON.stringify(entry[key])}`).join("\n");
  return `---\n${frontmatter}\n---\n${entry.body || ""}`;
}
function parseMarkdown(source) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) throw new Error("Session file must begin with YAML frontmatter delimited by ---. ");
  const entry = { body: match[2] };
  for (const line of match[1].split(/\r?\n/)) {
    const separator = line.indexOf(":");
    if (separator < 1) continue;
    const key = line.slice(0, separator).trim();
    const raw = line.slice(separator + 1).trim();
    entry[key] = parseYamlValue(raw);
  }
  for (const field of ENTRY_FIELDS.filter((field) => field !== "about")) {
    if (!(field in entry)) throw new Error(`Session file is missing required frontmatter field: ${field}`);
  }
  if (!("about" in entry)) entry.about = null;
  return entry;
}
function parseYamlValue(raw) {
  try { return JSON.parse(raw); } catch { return raw === "null" ? null : raw.replace(/^['"]|['"]$/g, ""); }
}
function searchableText(entry) {
  return [entry.topic, entry.situation, entry.logic, entry.emotion, entry.summary, entry.raw_input, entry.audio_ref, entry.about, entry.body, ...(entry.categories || []), ...(entry.tags || [])]
    .filter((value) => typeof value === "string").join("\n").toLocaleLowerCase();
}
